### ISSUE TITLE
Add to README.md .env configuration explanation

### ISSUE THREAD

**Issue by Grana69** [NFhbar/Token-Deployer#1]
I tried to migrate the contracts with this command:
`truffle.cmd deploy --network ganache`
I got this: 
`TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at Function.from (buffer.js:195:11)
    at new Buffer (buffer.js:170:17)
    at Object.<anonymous> (C:\Users\pervert_guy\Documents\github\Token-Deployer-master\truffle.js:7:25)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Function.Config.load (C:\Users\pervert_guy\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-config\index.js:259:1)
    at Function.Config.detect (C:\Users\pervert_guy\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-config\index.js:248:1)
    at Object.run (C:\Users\pervert_guy\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-core\lib\commands\migrate.js:35:1)
    at Command.run (C:\Users\pervert_guy\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-core\lib\command.js:101:1)
    at Object.<anonymous> (C:\Users\pervert_guy\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-core\cli.js:16:1)
    at __webpack_require__ (C:\Users\pervert_guy\AppData\Roaming\npm\node_modules\truffle\build\webpack:\webpack\bootstrap d593bf949760f66481d4:19:1)
    at C:\Users\pervert_guy\AppData\Roaming\npm\node_modules\truffle\build\webpack:\webpack\bootstrap d593bf949760f66481d4:65:1
    at Object.<anonymous> (C:\Users\pervert_guy\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:71:10)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3`
So, to fix that it the project needs a .env file in the root folder with the following variable:
`RINKEBY_PRIVATE_KEY = "KEY"`
"KEY" is the private key from rinkeby network, can be obtained from any connection with rinkeby ( geth, metamask, etc...)

**Comment by NFhbar** [comment]
Good catch! Fixed and closed.
